version: '3.4'

services:
  sampleproject:
    image: front-end-venuste
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000